[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g pnpm@11.5.1 --no-fund --no-audit",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"
